services:
  app:
    build:
      context: ./docker/php
    container_name: mind-flow
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - laravel

  web:
    image: nginx:latest
    container_name: laravel-vue-nginx
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql
    container_name: mind-flow-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mind-flow
      MYSQL_USER: mind-db
      MYSQL_PASSWORD: mind-db25
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel

volumes:
  db-data:

networks:
  laravel:
